version: '3.8'

services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    depends_on:
      - redis
    environment:
      REDIS_DNS: redis
      REDIS_PORT: 6379
    ports:
      - "9000:9000"

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    environment:
      BACKEND_DNS: backend

volumes:
  redis_data:
    driver: local
