apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  serviceName: "grafana-headless" 
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 472:472 /var/lib/grafana/"]
          volumeMounts:
            - mountPath: /var/lib/grafana/
              name: grafana-pv
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
          securityContext:
            runAsUser: 0
          env:
            - name: GF_SERVER_ROOT_URL
              value: "http://k8s-student3-ingress2-b8bfaaab6f-1896391073.eu-north-1.elb.amazonaws.com/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
  volumeClaimTemplates:
    - metadata:
        name: grafana-pv
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp2
