---
name: deploy

on:
  workflow_run:
    workflows: [Release Pipeline]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
      image: bitnami/kubectl:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make directory "~/.kube"
        run: mkdir -p ~/.kube
      - name: Injecting secrets
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
      - name: Apply Kubernetes manifests
        run: kubectl apply -f kubernetes/
      - name: update helm releases
        run: |
          sed -i "s/\(version: \).*/\1$(grep -oP 'version": "\K[^"]+' ./frontend/package.json)/" ./helm/fortune/fortune-application/frontend-values.yaml
          sed -i "s/\(version: \).*/\1$(grep -oP 'version": "\K[^"]+' ./backend/package.json)/" ./helm/fortune/fortune-application/backend-values.yaml
      - name: deploying helm charts
        working-directory: ./helm/helm-bin
        run: |
          chmod +x ./helm
          ./helm upgrade redis ../fortune/databases/ -f ../fortune/databases/redis-value.yaml -i
          ./helm upgrade backend ../fortune/fortune-application/ -f ../fortune/fortune-application/backend-values.yaml -i
          ./helm upgrade frontend ../fortune/fortune-application/ -f ../fortune/fortune-application/frontend-values.yaml -i
