---
name: deploy

on:
  workflow_run:
    workflows: [Go package]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
      image: bitnami/kubectl:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make directory "~/.kube"
        run: mkdir -p ~/.kube
      - name: Injecting secrets
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
      - name: Apply Kubernetes manifests
        run: kubectl apply -f kubernetes/
      - name: ls
        run: ls
      - name: deploying helm charts
        working-directory: ./helm/helm-bin
        run: |
          chmod +x ./helm
          ./helm helm install redis ../fortune/databases/ -f ../fortune/databases/redis-value.yaml
          ./helm helm install backend ../fortune/fortune-application/ -f ../fortune/fortune-application/backend-values.yaml
          ./helm helm install frontend ../fortune/fortune-application/ -f ../fortune/fortune-application/frontend-values.yaml
