name: deploy

on: [workflow_dispatch]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    container:
      image: bitnami/kubectl:latest
    steps:
      - run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
      - run: kubectl get all
