---
name: deploy

on:
  workflow_run:
    workflows: [Go package]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
      image: bitnami/kubectl:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make directory "~/.kube"
        run: mkdir -p ~/.kube
      - name: Injecting secrets
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
      - name: Apply Kubernetes manifests
        run: kubectl apply -f kubernetes/
